[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.eggs
  | \.egg-info
  | \.idea
  | build
  | dist
  | migrations
)/
'''
skip-string-normalization = true
